/**
 * Generates a well-formatted HTML file for printing / saving as PDF
 */
export function exportTripAsHTML(trip) {
  const sel = trip?.userSelection || {}
  const data = trip?.tripData?.tripData || {}
  const location = sel.location?.properties?.formatted || 'My Trip'
  const days = sel.noOfDays || '?'
  const budget = sel.budget || ''
  const traveler = sel.traveler || ''
  const itinerary = data.itinerary || []
  const hotels = data.hotels || []
  const notes = data.notes || ''

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>${location} — Trip Itinerary</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1e293b; background: #fff; padding: 32px; max-width: 800px; margin: 0 auto; }
    .header { background: linear-gradient(135deg, #4F6EF7, #7C3AED); color: white; padding: 32px; border-radius: 20px; margin-bottom: 32px; }
    .header h1 { font-size: 2rem; font-weight: 800; margin-bottom: 8px; }
    .header p { opacity: 0.85; font-size: 0.95rem; }
    .badges { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px; }
    .badge { padding: 4px 14px; border-radius: 100px; background: rgba(255,255,255,0.2); font-size: 0.8rem; font-weight: 600; }
    .section-title { font-size: 1.25rem; font-weight: 700; margin: 28px 0 16px; color: #1e293b; display: flex; align-items: center; gap: 8px; }
    .section-title::before { content: ''; display: inline-block; width: 4px; height: 20px; background: #4F6EF7; border-radius: 2px; }
    .day-block { margin-bottom: 24px; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; }
    .day-header { background: #f8fafc; padding: 12px 20px; font-weight: 700; font-size: 1rem; border-bottom: 1px solid #e2e8f0; }
    .activity { padding: 12px 20px; border-bottom: 1px solid #f1f5f9; }
    .activity:last-child { border-bottom: none; }
    .activity-name { font-weight: 600; font-size: 0.9rem; color: #1e293b; margin-bottom: 4px; }
    .activity-desc { font-size: 0.8rem; color: #64748b; line-height: 1.5; margin-bottom: 6px; }
    .activity-meta { display: flex; gap: 16px; font-size: 0.75rem; color: #94a3b8; }
    .hotel-card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
    .hotel-name { font-weight: 700; font-size: 0.95rem; margin-bottom: 4px; }
    .hotel-meta { font-size: 0.8rem; color: #64748b; }
    .notes { background: #fefce8; border: 1px solid #fde047; border-radius: 12px; padding: 16px; font-size: 0.875rem; color: #854d0e; line-height: 1.6; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 0.8rem; color: #94a3b8; }
    @media print { body { padding: 16px; } .header { border-radius: 8px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>✈️ ${location}</h1>
    <p>AI-Generated Travel Itinerary by TripCortex</p>
    <div class="badges">
      <span class="badge">📅 ${days} Days</span>
      ${budget ? `<span class="badge">💰 ${budget}</span>` : ''}
      ${traveler ? `<span class="badge">👥 ${traveler}</span>` : ''}
    </div>
  </div>

  ${itinerary.length > 0 ? `
  <div class="section-title">Daily Itinerary</div>
  ${itinerary.map(day => `
    <div class="day-block">
      <div class="day-header">${day.day}</div>
      ${(day.activities || []).map(act => `
        <div class="activity">
          <div class="activity-name">${act.placeName || ''}</div>
          <div class="activity-desc">${act.placeDetails || ''}</div>
          <div class="activity-meta">
            ${act.timeSpent ? `<span>🕒 ${act.timeSpent}</span>` : ''}
            ${act.ticketPricing ? `<span>🎟️ ${act.ticketPricing}</span>` : ''}
          </div>
        </div>
      `).join('')}
    </div>
  `).join('')}
  ` : ''}

  ${hotels.length > 0 ? `
  <div class="section-title">Hotel Recommendations</div>
  <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px">
    ${hotels.map(h => `
      <div class="hotel-card">
        <div class="hotel-name">${h.hotelName || ''}</div>
        <div class="hotel-meta">📍 ${h.hotelAddress || ''}</div>
        <div class="hotel-meta">⭐ ${(h.rating || '').split('(')[0]} &nbsp; 💰 ${h.price_per_night_usd || h.price_range || ''}</div>
      </div>
    `).join('')}
  </div>
  ` : ''}

  ${notes ? `
  <div class="section-title">Travel Tips</div>
  <div class="notes">${notes}</div>
  ` : ''}

  <div class="footer">
    Generated by TripCortex AI &nbsp;·&nbsp; ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}
  </div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${location.replace(/[^a-z0-9]/gi, '_')}_itinerary.html`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Copy trip summary text to clipboard
 */
export async function copyTripSummary(trip) {
  const sel = trip?.userSelection || {}
  const data = trip?.tripData?.tripData || {}
  const location = sel.location?.properties?.formatted || 'My Trip'
  const days = sel.noOfDays || '?'

  let text = `✈️ ${location} — ${days}-day Trip\n\n`

  const itinerary = data.itinerary || []
  itinerary.forEach(day => {
    text += `📅 ${day.day}\n`
    ;(day.activities || []).forEach(act => {
      text += `  • ${act.placeName}\n`
    })
    text += '\n'
  })

  text += `\nGenerated by TripCortex AI — tripcortex.app`
  await navigator.clipboard.writeText(text)
}
